### ISSUE TITLE
Request for pretrained model!

### ISSUE THREAD

**Issue by KarinSu97** [jordan-bird/eeg-feature-generation#1]
Hi, 

    I want to know if the pretrained model is provided. I would be highly appreciated if you share your trained model. 

Thanks a lot!

Karin.

**Comment by jetexh** [comment]
> Hi,
> 
> ```
> I want to know if the pretrained model is provided. I would be highly appreciated if you share your trained model. 
> ```
> 
> Thanks a lot!
> 
> Karin.

Hey Karin,

I am also looking for the pretrained model of EEG emotion classification using the muse headset. Let me know if you manage to get ahold of this, or anything similar.

Regards,
Jethro

**Comment by jordan-bird** [comment]
Hi,

I will upload the trained models soon when I can, but here are some resources that will probably help you a lot more since they also come with videos and source code:

[Gabriel Atkin's step-by-step YouTube tutorial where he uses our EEG Emotions dataset](https://www.youtube.com/watch?v=IAQdqaoHrfE)

[15 individual notebooks using different methods to classify the EEG emotions dataset](https://www.kaggle.com/birdy654/eeg-brainwave-dataset-feeling-emotions/code)

[Sahil Jain's tutorial where he shows how to apply several SciKit Learn models to the mental state classification dataset](https://www.kaggle.com/j105sahil/eeg-brainwave-dataset-mental-state)

Since these datasets are becoming popular, I'll probably make a repo soon with a code tutorial for a feature extraction + classification pipeline. Instructions for feature extraction are given in the readme of this repo and the outputs can then be used with any of the above code tutorials.

**Comment by KarinSu97** [comment]
> Hi,
> 
> I will upload the trained models soon when I can, but here are some resources that will probably help you a lot more since they also come with videos and source code:
> 
> [Gabriel Atkin's step-by-step YouTube tutorial where he uses our EEG Emotions dataset](https://www.youtube.com/watch?v=IAQdqaoHrfE)
> 
> [15 individual notebooks using different methods to classify the EEG emotions dataset](https://www.kaggle.com/birdy654/eeg-brainwave-dataset-feeling-emotions/code)
> 
> [Sahil Jain's tutorial where he shows how to apply several SciKit Learn models to the mental state classification dataset](https://www.kaggle.com/j105sahil/eeg-brainwave-dataset-mental-state)
> 
> Since these datasets are becoming popular, I'll probably make a repo soon with a code tutorial for a feature extraction + classification pipeline. Instructions for feature extraction are given in the readme of this repo and the outputs can then be used with any of the above code tutorials.

Thank you very much for your reply, I‘m looking forward to it. Good luck!
Karin.
